---
title: 2715. 执行可取消的延迟函数
description: LeetCode 2715. 执行可取消的延迟函数题解，Timeout Cancellation，包含解题思路、复杂度分析以及完整的 JavaScript 代码实现。
keywords:
  - LeetCode
  - 2715. 执行可取消的延迟函数
  - 执行可取消的延迟函数
  - Timeout Cancellation
  - 解题思路
---

# 2715. 执行可取消的延迟函数

🟢 <font color=#15bd66>Easy</font>&emsp; 🔗&ensp;[`力扣`](https://leetcode.cn/problems/timeout-cancellation) [`LeetCode`](https://leetcode.com/problems/timeout-cancellation)

## 题目

Given a function `fn`, an array of arguments `args`, and a timeout `t` in
milliseconds, return a cancel function `cancelFn`.

After a delay of `cancelTimeMs`, the returned cancel function `cancelFn` will
be invoked.

> 
> 
> 
> 
> 
> setTimeout(cancelFn, cancelTimeMs)
> 
> 

Initially, the execution of the function `fn` should be delayed by `t`
milliseconds.

If, before the delay of `t` milliseconds, the function `cancelFn` is invoked,
it should cancel the delayed execution of `fn`. Otherwise, if `cancelFn` is
not invoked within the specified delay `t`, `fn` should be executed with the
provided `args` as arguments.



**Example 1:**

> Input: fn = (x) => x * 5, args = [2], t = 20
> 
> Output: [{"time": 20, "returned": 10}]
> 
> Explanation: 
> 
> const cancelTimeMs = 50;
> 
> const cancelFn = cancellable((x) => x * 5, [2], 20);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> The cancellation was scheduled to occur after a delay of cancelTimeMs (50ms), which happened after the execution of fn(2) at 20ms.

**Example 2:**

> Input: fn = (x) => x**2, args = [2], t = 100
> 
> Output: []
> 
> Explanation: 
> 
> const cancelTimeMs = 50;
> 
> const cancelFn = cancellable((x) => x**2, [2], 100);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> The cancellation was scheduled to occur after a delay of cancelTimeMs (50ms), which happened before the execution of fn(2) at 100ms, resulting in fn(2) never being called.

**Example 3:**

> Input: fn = (x1, x2) => x1 * x2, args = [2,4], t = 30
> 
> Output: [{"time": 30, "returned": 8}]
> 
> Explanation: const cancelTimeMs = 100;
> 
> const cancelFn = cancellable((x1, x2) => x1 * x2, [2,4], 30);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> The cancellation was scheduled to occur after a delay of cancelTimeMs (100ms), which happened after the execution of fn(2,4) at 30ms.

**Constraints:**

  * `fn` is a function
  * `args` is a valid JSON array
  * `1 <= args.length <= 10`
  * `20 <= t <= 1000`
  * `10 <= cancelTimeMs <= 1000`


## 题目大意

给定一个函数 `fn` ，一个参数数组 `args` 和一个以毫秒为单位的超时时间 `t` ，返回一个取消函数 `cancelFn` 。

在 `cancelTimeMs` 的延迟后，返回的取消函数 `cancelFn` 将被调用。

> 
> 
> 
> 
> 
> setTimeout(cancelFn, cancelTimeMs)
> 
> 

最初，函数 `fn` 的执行应该延迟 `t` 毫秒。

如果在 `t` 毫秒的延迟之前调用了函数 `cancelFn`，它应该取消 `fn` 的延迟执行。否则，如果在指定的延迟 `t` 内没有调用
`cancelFn`，则应执行 `fn`，并使用提供的 `args` 作为参数。



**示例 1:**

> 
> 
> 
> 
> 
> **输入：** fn = (x) => x * 5, args = [2], t = 20
> 
> **输出：**[{"time": 20, "returned": 10}]
> 
> **解释：**
> 
> const cancelTimeMs = 50;
> 
> const cancelFn = cancellable((x) => x * 5, [2], 20);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> 取消操作被安排在延迟了 cancelTimeMs（50毫秒）后进行，这发生在 fn(2) 在20毫秒时执行之后。

**示例 2：**

> 
> 
> 
> 
> 
> **输入：** fn = (x) => x**2, args = [2], t = 100
> 
> **输出：**[]
> 
> **解释：**
> 
> const cancelTimeMs = 50;
> 
> const cancelFn = cancellable((x) => x**2, [2], 100);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> 取消操作被安排在延迟了 cancelTimeMs（50毫秒）后进行，这发生在 fn(2) 在100毫秒时执行之前，导致 fn(2) 从未被调用。
> 
> 

**示例 3：**

> 
> 
> 
> 
> 
> **输入：** fn = (x1, x2) => x1 * x2, args = [2,4], t = 30
> 
> **输出：**[{"time": 30, "returned": 8}]
> 
> **解释：**
> 
> const cancelTimeMs = 100;
> 
> const cancelFn = cancellable((x1, x2) => x1 * x2, [2,4], 30);
> 
> setTimeout(cancelFn, cancelTimeMs);
> 
> 
> 
> 取消操作被安排在延迟了 cancelTimeMs（100毫秒）后进行，这发生在 fn(2,4) 在30毫秒时执行之后。
> 
> 



**提示：**

  * `fn` 是一个函数
  * `args` 是一个有效的 JSON 数组
  * `1 <= args.length <= 10`
  * `20 <= t <= 1000`
  * `10 <= cancelTimeMs <= 1000`


## 解题思路

#### 复杂度分析

- **时间复杂度**：`O()`，
- **空间复杂度**：`O()`，

## 代码

```javascript

```